### ISSUE TITLE
Default classes for bootstrap setup in demo site?

### ISSUE THREAD

**Issue by testbird** [Flowpack/Flowpack.Listable#2]
May be it makes sense to detect or configure a framework (like bootstrap in the demo site), and have the list objects automatically render withe the corresponding css IDs and classes.

**Comment by dimaip** [comment]
Ughh no, there are very many CSS frameworks, can't cater to all of them. But it should be made clear for integrator how to specify the needed classes.

**Comment by testbird** [comment]
Yes, don't worry about any particular framework.

I don't know, but if it is feasable, maybe flow or neos could have something like a central variable for each site to indicate the default framework, and all the packages could allow users to contribute framework specific configuration files (simmilar to translations).
