### ISSUE TITLE
Routing seems not to work

### ISSUE THREAD

**Issue by htuscher** [Flowpack/Flowpack.Listable#21]
According to the Routes.yaml which should be auto-included, I should be able to use URLs like `/de/news~p2.html`, correct?
This seems to be broken.

**Comment by dimaip** [comment]
@hhoechtl thanks for reporting! Can you please try figure out why that happens?

**Comment by htuscher** [comment]
All I could figure out so far is this:

```
application@937244be946b:/app$ ./flow configuration:validate --type Routes
Validating Routes configuration

All Valid!

application@937244be946b:/app$ ./flow routing:list
Currently registered routes:
1. __form/{formIdentifier}/{presetName}(/{locale})                              Onedrop.AjaxForm :: Ajax Form Endpoint
2. neos/media/browser/assets(/{@action}).{@format}                              Neos.Media.Browser :: Media Browser
3. neos/media/browser/images(/{@action}).{@format}                              Neos.Media.Browser :: Image Browser
4. media/thumbnail/{thumbnail}                                                  Neos.Media :: Thumbnail
5. {node}<pageSeparator>{--listable-paginate.currentPage}<defaultUriSuffix>     Flowpack.Listable :: Paginate for Flowpack.Listable:Listable

application@937244be946b:/app$ ./flow routing:show 5
Information for route 5:
  Name: Flowpack.Listable :: Paginate for Flowpack.Listable:Listable
  Pattern: {node}<pageSeparator>{--listable-paginate.currentPage}<defaultUriSuffix>
  Defaults:
    - @package => Neos.Neos
    - @controller => Frontend\Node
    - @format => html
    - @action => show
Notice: Array to string conversion in /opt/tmp/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Command_RoutingCommandController.php line 85
```

But looking in the RoutingCommandController it's just not expected to print the sub-Array at this point. So it has probably nothing to do with this issue. I'll keep digging.

**Comment by htuscher** [comment]
Ok, from debugging I can say that the path given to the `FrontendNodeRoutePartHandler` is too long. It should only receive `/de/news` but receives `/de/news~p2` from the routing which it can't handle, because it's not a valid node path.
Therefore the splitting of the uri path seems to have a problem.

**Comment by htuscher** [comment]
Ok, the splitString that is assigned to the `FrontendNodeRoutePartHandler` is `<pageSeperator>` but should be `~p` (probably) so it seems that its not being replaced properly.
If I change the uriPattern to `'{node}~p{--listable-paginate.currentPage}<defaultUriSuffix>'` at least the `FrontendNodeRoutePartHandler` matches a node correctly, but the entire route still doesn't match.

**Comment by htuscher** [comment]
```
-
  name: 'Paginate for Flowpack.Listable:Listable'
  uriPattern: '{node}~p{--listable-paginate.currentPage}'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--listable-paginate':
      '@package': ''
      '@subpackage': ''
      '@controller': ''
      '@action': 'index'
      'currentPage': '1'
  routeParts:
    node:
      handler: Neos\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE
```

Seems to be the only working configuration where matching and resolving works.
