### ISSUE TITLE
Version consistency

### ISSUE THREAD

**Issue by htuscher** [Flowpack/Flowpack.Listable#26]
The current version tag 2.0.2 should be 3.0 as it's a breaking change and makes every package that depends on Listable incompatible.

**Comment by dimaip** [comment]
It was an accident, sorry for the trouble caused. I fixed the version now and added a warning about breaking changes.

**Comment by htuscher** [comment]
@dimaip You still need to remove the 2.0.2 tag or it will continue cause trouble

**Comment by dimaip** [comment]
Thanks, did so.
I thought I renamed the old tag, but no.
