### ISSUE TITLE
skip or offset

### ISSUE THREAD

**Issue by testbird** [Flowpack/Flowpack.Listable#3]
I could not find offsets (skipping to list the first n items (as they may be rendered in full lengh just above the list).

**Comment by dimaip** [comment]
You can use [slice](https://neos.readthedocs.org/en/1.2/Appendixes/FlowQueryOperationReference.html#slice) FQ operation to make an offset. Is this what you want or do you want something specific in the package itself?

**Comment by dimaip** [comment]
Maybe it makes sense to make it part of the package itself, just for convenience?

**Comment by testbird** [comment]
Thanks for pointing me to `slice`. The linked doc mentions "offset" but gives me no idea how to use it.

**Comment by dimaip** [comment]
So to get 10 items offsetting by 5, you'd write smth like `.slice(5, 10)`

**Comment by dimaip** [comment]
I've added this feature, see linked commit. Is this the kind of thing which you wanted?

**Comment by testbird** [comment]
Thank you for the slice example.
