### ISSUE TITLE
date dependant listings

### ISSUE THREAD

**Issue by testbird** [Flowpack/Flowpack.Listable#4]
Allow to limit and paginate based on date property? For example, show only past/next month or year, and paginate to past/next year.

**Comment by testbird** [comment]
Collaboration possibilities for a Neos community events package:

https://github.com/ttreeagency/Ttree.Plugin.MicroEvent
Already contains some human date interval implemantations, currently defines own listings.

https://github.com/khuppenbauer/MapSeven.Calendar
Integrated a js calendar, but uses google as data store.

**Comment by dimaip** [comment]
Hmm you mean like have a calendar view with ability to select month and see all relevant news?
Technically it is possible already with custom FlowQuery, maybe could go in as an example. Will leave this one open for now, but not sure I have time to implement it.
Maybe you would want to do it on top of Sfi.Listable?

**Comment by testbird** [comment]
Yes, it's good when you leave it open so visitors get an overview.

> Hmm you mean like have a calendar view with ability to select month and see all relevant news?
> Not a full blown calendar view, just the ability to list all "listables" of this year, and paginate to next year, last year, and the year before... (-2015.html?)

I can imagine that custom queries can limit the collection according to date values. But do they also allow the paginated list to jump back and forth for example by one month? An example query  as a starting pointer would be nice.

I suspect that
https://github.com/ttreeagency/Ttree.Plugin.MicroEvent/blob/master/Classes/Ttree/Plugin/MicroEvent/TypoScript/HumanDateIntervalImplementation.php
implements this, but maybe it would be more generic to define the width of the time window for which items are listed (interval) in hours, or seconds.

I think Community.Events would stay a separate package (and node type), and that a calander view would be an addition to Community.Events.  Just added them as package examples that could use Listable to get their lists, and that may already implement some date based filtering example code.

**Comment by dimaip** [comment]
It's funny, the first time I commented I thought that this issue belongs to Community.News, and not Sfi.Listable. Well, of course, in this case the calendar itself does not belong to Sfi.Listable, but it could provide examples how to query by date range, maybe provide some helper FQ operation for that.

To implement pagination by date we'd need a custom fluid pagination widget. Not sure if it could go into this package or be a separate package. Maybe making it separate would help keep this package more lean, the kind of do one thing and do it well approach.

**Comment by testbird** [comment]
Ok yes, once it works pagination by date should be a core flow/neos feature.
