### ISSUE TITLE
Replace deprecated Fusion prototypes

### ISSUE THREAD

**Issue by auwaerter** [Flowpack/Flowpack.Listable#48]
According to the docs:
- [Neos.Fusion:Array](https://neos.readthedocs.io/en/stable/References/NeosFusionReference.html#neos-fusion-array) being used [here](https://github.com/Flowpack/Flowpack.Listable/blob/master/Resources/Private/Fusion/List.fusion#L18) and [here](https://github.com/Flowpack/Flowpack.Listable/blob/master/Resources/Private/Fusion/PaginatedCollection.fusion#L12) is deprecated and should be replaced with [Neos.Fusion:Join](https://neos.readthedocs.io/en/stable/References/NeosFusionReference.html#neos-fusion-join)
- [Neos.Fusion:RawArray](https://neos.readthedocs.io/en/stable/References/NeosFusionReference.html#neos-fusion-rawarray) being used [here](https://github.com/Flowpack/Flowpack.Listable/blob/master/Resources/Private/Fusion/PaginatedCollection.fusion#L13) is deprecated and should be replaced with [Neos.Fusion:DataStructure](https://neos.readthedocs.io/en/stable/References/NeosFusionReference.html#neos-fusion-datastructure). 
- [Neos.Fusion:Collection](https://neos.readthedocs.io/en/stable/References/NeosFusionReference.html#neos-fusion-collection) being used [here](https://github.com/Flowpack/Flowpack.Listable/blob/master/Resources/Private/Fusion/Collection.fusion#L1) and [here](https://github.com/Flowpack/Flowpack.Listable/blob/master/Resources/Private/Fusion/Pagination.fusion#L23) is deprecated and should be replaced with [Neos.Fusion:Loop](https://neos.readthedocs.io/en/stable/References/NeosFusionReference.html#neos-fusion-loop)

**Comment by ahaeslich** [comment]
Thank you for this issue. For Neos 9 we will need this adjustments as the deprecated Fusion prototypes will be removed: https://github.com/neos/neos-development-collection/pull/4537
